language: ruby
cache: bundler
rvm:
    - 2.2.4

before_script:
    - cp config/database.yml.travis config/database.yml
    - psql -c 'create database travis_ci_test' -U postgres
    - rake db:migrate

script:
    - bundle exec rake
    - bundle exec rake coveralls:push
